version: '3'

services:
  db:
    container_name: express_prj_pg
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5414:5432"

  pgadmin:
    container_name: express_prj_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: emelyanov@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5053:80"